### ISSUE TITLE
Perhaps "Go" is not the best trigger... Go beat you to it...

### ISSUE THREAD

**Issue by AlexJ-StL** [jgravelle/GroqNow#1]
If anyone has the Go programming language installed on there computer they should get an error stating, "Go is a tool for managing Go source code."

Perhaps you could use "Go-Now" or "Now-Go". 

Just a suggestion.

**Comment by jgravelle** [comment]
Per Co-Pilot:

"...if you have a batch file named go.bat in your current directory, it will take precedence over the go command from the Go programming language when you type go at the command line. This is because the command prompt will first look for an executable file in the current directory before searching the directories listed in the PATH environment variable..."

**Comment by AlexJ-StL** [comment]
Well, I'll have to speak with Co-Pilot because I still get an error despite being in the correct directory. Curious indeed.

**Comment by jgravelle** [comment]
That IS weird.  This is happening in Windows™...?

**Comment by AlexJ-StL** [comment]
> That IS weird. This is happening in Windows™...?

Yes. W11 23H2

Sorry for the delayed response, but I appreciate you following up again after closing the issue. I didn't expect you to pay any further attention. 

That said, I haven't tried it again since I first posted. Had a couple of fires raging and got distracted. I will give it another "go" this evening... I'm sure it was an error/oversight on my end somewhere. There is always something conflicting on my Windows machine.

Again, thank you for following up and thanks for all you've been doing! I don't know where you find the time, energy, or patience, but I am glad can.

Cheers
